services:
  frontend:
    container_name: kots-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_MODE: ${APP_MODE:-development}
        BACKEND_BASE_URL: ${BACKEND_BASE_URL:-}
    environment:
      APP_MODE: ${APP_MODE:-development}
    ports:
      - "${FRONTEND_PORT:-4200}:${CONTAINER_HTTP_PORT:-80}"
      - "${FRONTEND_ALT_PORT:-10000}:${CONTAINER_ALT_PORT:-10000}"
    restart: unless-stopped
