services:
  frontend:
    container_name: kots-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4200}:${CONTAINER_HTTP_PORT:-80}"
      - "${FRONTEND_ALT_PORT:-10000}:${CONTAINER_ALT_PORT:-10000}"
    restart: unless-stopped
